### ISSUE TITLE
reopen Obsidian will auto hide window

### ISSUE THREAD

**Issue by subframe7536** [dragonwocky/obsidian-tray#1]
reproduce: hide window -> quit Obsidian using tray context menu -> open Obsidian -> auto hide window

is this a feature or bug?

**Comment by dragonwocky** [comment]
It's a feature, check the description of the "Run in background" option:
![image](https://user-images.githubusercontent.com/16874139/203662160-2879a7ed-b955-443f-b4a3-382892a89b2d.png)

Ideally it would only do that when Obsidian is launched automatically on system startup, going directly to the tray so it's out of the way until you need it, but I haven't found a reliable way to detect the difference between a startup launch and a manual launch of the app yet, so this is how it is for now.

**Comment by subframe7536** [comment]
get it, thanks for all your hard work😊

**Comment by hustrjh** [comment]
Hi @dragonwocky. I wanna share my idea about solving the problem.

I think **`tray`** could record the time when Obsidian launches and the time when System startups. If the time interval is larger than specific value which could be set by users. It means this launch is a manual launch and **`tray`** needn't hide the app.

I hope this will help. Actually it's really wierd that Obsidian automatically hides when I manually open it.

**Comment by dragonwocky** [comment]
> I think tray could record the time when Obsidian launches and the time when System startups. If the time interval is larger than specific value which could be set by users. It means this launch is a manual launch and tray needn't hide the app.

How do you suggest recording when the system starts? I haven't found anything in the Electron docs about checking the time since boot, and the app itself isn't running until after the system has finished booting, so for obsidian-tray to record startup time it would need to know that it was opening for the first time after boot already - which brings us back to the initial cause of this problem.

> Actually it's really wierd that Obsidian automatically hides when I manually open it.

If you have combined the `run in background` and `launch on startup` options, you shouldn't ever need to manually open the app. It opens automatically for you when you power on your computer, and then continues running in the background ready to be called to focus by clicking the icon or using the hotkey. If you intend to manually close and reopen the app, you probably shouldn't be using the `run in background` option.

**Comment by hustrjh** [comment]
## My problem
To tell the truth, the function I need most is that Obsidian will stay in background.

As you know so many plugins I've set up really slow the startup speed of Obsidian. Thus Obsidian staying in background saves me a lot of time. So I just need **`Run in background`** function without **`Launch on startup`**.
![image](https://user-images.githubusercontent.com/69783980/209663099-b25fd7eb-fca2-4c78-a731-7ebfef3f147a.png)
Then I will encounter the case that after opening Obsidian manually the app hides automatically.

## My suggestion
I'm sorry that I'm not familiar with Electron and Javascript. I wonder if there is any method to get System startup time. All I know is `cmd` and `powershell` method. I don't know if JS could get that value. If this problem could be solved, **`obsidian-tray`** will be perfect. Thanks for your reply. 😄

**Comment by dragonwocky** [comment]
> Then I will encounter the case that after opening Obsidian manually the app hides automatically.

Oh, I see. That's a bug. The app should only hide automatically if `Launch on startup` and `Run in background` are both enabled. I've created a new issue for that here, I'll fix it when I can: #3

> I don't know if JS could get that value.

As far as I know, it can't.

**Comment by hustrjh** [comment]
Thank you for your effort! I love this plugin. 👍
