### ISSUE TITLE
Quick note date format displays hectic file names

### ISSUE THREAD

**Issue by Jeromandres** [dragonwocky/obsidian-tray#17]
Preview and create quick note file names do not match what is entered with keyboard
The keys I enter are correctly displayed in the fill-in box on the right but are erroneous in the "Preview" text, as well as created file names

There are strange remapping of keys: on my French AZERTY keyboard, most keys display the correct preview, but some transfrom into incorrect mappings:
 - 'Q' translates into '2'
 - 'k' translates into '14'
 - 'n' translate into 'AD'
 - 'e' translates into '2'
![2023-05-23 14_05_30-Démarrer](https://github.com/dragonwocky/obsidian-tray/assets/44743048/be5be851-f127-4ba3-b3fb-42b45dbc4ab7)

The errors are systematic -- it means they are not random

It prevents from selecting a filename and a folder to store the quick notes into.

**Comment by dragonwocky** [comment]
@Jeromandres if you check the format string definition in the Moment.js docs (which is linked in the option description), you'll see that this is expected behaviour: https://momentjs.com/docs/#/displaying/format/. `Q` gets replaced by the quarter, `k` gets replaced with the hour in 24hr time, `N` gets replaced with the era, and `e` gets replaced with the day of the week.

You can wrap characters in `[square brackets]` to avoid character replacements e.g. doing `[Quick Note,] YYYY-MM-DD` instead of `Quick Note, YYYY-MM-DD`.
