### ISSUE TITLE
CmdOrCtrl+Shift+Tab global hotkey conflicts with Chrome

### ISSUE THREAD

**Issue by NelsonMinar** [dragonwocky/obsidian-tray#19]
Thank you for Tray! It's very impressive; I wouldn't have thought it'd be possible to do a UI like this with an addon.

One thing that confused me; Tray [by default](https://github.com/dragonwocky/obsidian-tray/blob/a5abaf32e7740fae2dedfb997a89a77f2c90980b/main.js#L271) binds `CmdOrCtrl+Shift+Tab` to "Toggle window focus hotkey". That's also a Chrome hotkey which means "previous tab". It took me awhile to figure out why pressing it with Chrome focussed in Windows kept opening Obsidian, especially since first I looked at Obsidian's own hotkeys which has another binding for `CmdOrCtrl+Shift+Tab`.

I don't really use global hotkeys so I just disabled them all and I'm happy. But you might want to consider whether it's a good default. (Or just close this issue; it's definitely a stylistic choice.)

**Comment by dragonwocky** [comment]
Happy to change the default if you've got a better suggestion.

Most hotkeys are taken up by one app or other so I'm not too concerned by a conflict with another app - there're so many different hotkeys available that it'll always conflict with something, that's partly why it's configurable. Plus, I do kinda expect people installing this to actually go through the options it ships with and customise the behaviours to their liking, since it is more of a power user extension.

I can see why overriding a default Obsidian hotkey wouldn't be ideal, though. In order to register the hotkey globally and not just as an in-app command it has to be configured through the extension's own options instead of Obsidian's hotkey settings, so I hadn't noticed that conflict yet myself. Thanks.

**Comment by tommdq** [comment]
Is it possible to set "windows" key as a modifier? If so, how? I tried "win" and "windows" but it didn't work

**Comment by VialesProductions** [comment]
@tommdq you need to use `Super` [source](https://www.electronjs.org/docs/latest/api/accelerator#platform-notice)

I've personally bound the "Toggle window focus hotkey" as "Super+Shift+Tab" (which is Win + Shift + Tab for me, on Win 11)

**Comment by NelsonMinar** [comment]
I feel bad saying this, but Win-Shift-Tab has a meaning in Windows already. It's paired with Win-Tab and scrolls backwards through windows on the desktop. I think it's the same in MacOS: Shift-Command-Tab changes windows. So now instead of overriding a single popular app's keybindings (Chrome) Tray will be trying to override the whole OS.

I don't have a good solution or alternate keybinding to suggest. I disable them in Obsidian and Tray, myself.

**Comment by dragonwocky** [comment]
@NelsonMinar are you sure you're not thinking of <kbd>Alt + Shift + Tab</kbd>? <kbd>Win + Tab</kbd> opens with window switcher and <kbd>Win + Shift + Tab</kbd> doesn't do anything for me.

In that case, though, I'm thinking I'll put it back to how it was before and just leave it as-is. There will always be conflicts, because every app and OS registers hundreds of hotkeys, so I'd rather leave it up to users to pick which ones they want to prioritise and which ones they want to rebind.

**Comment by NelsonMinar** [comment]
Oops sorry, you are right about my confusion. Win + Shift + Tab doesn't seem bound to anything.
