### ISSUE TITLE
Alt+F4 quits Obsidian despite Run in Background

### ISSUE THREAD

**Issue by naquad** [dragonwocky/obsidian-tray#3]
Obsidian version: 1.0.3
Electron version: 18.3.15
obsidian-tray: master
OS: Linux
DE: Xfce 4

I've checked the Run in Background setting, just in case I've restarted Obsidian, and made sure the setting is set.

Pressing the window's close icon minimizes to the tray, all good.

Pressing Altr+F4 (window managers close window action) quits Obsidian.

**Comment by dragonwocky** [comment]
This is intended behaviour. The "Run in background" feature runs the app in the background when interacted with normally, it isn't there to prevent force-quitting the app e.g. via <kbd>Alt+F4</kbd> or using the "Quit" action in the tray menu (that comes a little too close to acting like malware for my taste).

If you would like to hide the app's windows instead of quitting them, you can use the "toggle window focus hotkey" instead of <kbd>Alt+F4</kbd>.

**Comment by dragonwocky** [comment]
@naquad FYI this behaviour has changed with the latest release, <kbd>Alt+F4</kbd> now minimises windows to the tray instead of quitting the app.
